export class Artista {
    id:number=0;
    nombre:String=""
    apellido:String=""
    pretskit:String=""
    seudonimo:String=""
    img:String=""
    ubicacion:String=""
    img_list:String=""
    soundcloud:String=""
    instagram:String=""
    spotify:String=""
    youtube:String=""
    mail:String=""
    track:String;
    video:String;
    tiktok:String;
    descripcion:String=""
}